version: '3.8'

services:
  service-position:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"  # Expose le port 8000 sur votre machine pour accéder à l'application sur le port 8080 du conteneur
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/locationdatabase  # Utilisez "mysql" comme hôte pour MySQL
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - app-network

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"  # Expose MySQL sur le port 3307 pour éviter les conflits avec une autre installation locale de MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: locationdatabase
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
